server:
  port: 8082
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      database: report-service
      port: 27017
      host: localhost